# Generated by Django 5.0.6 on 2024-07-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_alter_ngos_category_delete_categories'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisations', models.ManyToManyField(to='NGO.ngos')),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile')),
            ],
        ),
    ]
