# Generated by Django 5.0.6 on 2024-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
