# Generated by Django 5.0.6 on 2024-07-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_alter_ngos_category_delete_categories'),
        ('Users', '0003_alter_userprofile_image_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngos_volunteering', models.ManyToManyField(related_name='volunteers', to='NGO.ngos')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile')),
            ],
        ),
    ]
