# Generated by Django 5.0.6 on 2024-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngos',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
